### PR TITLE
Add axios config for bitcoin related apis

### PR DESCRIPTION
**Pull request by nothing0012**
Adding a axiosConfig so that the client to fine tune some axios client settings.

- Most are formatting changes
- Added an optional field in `MempoolConfig`

### CODE REVIEW

**Comment by Ibrahim7388** [comment]
[ethereum_evm_illustrated.pdf](https://github.com/mempool/mempool.js/files/11239264/ethereum_evm_illustrated.pdf)

**Comment by Ibrahim7388** [comment]
ethereum-network-utiliza

**Comment by Ibrahim7388** [comment]
[mempool.js-2.2.4.zip](https://github.com/mempool/mempool.js/files/11262744/mempool.js-2.2.4.zip)

**Comment by Ibrahim7388** [comment]
Purshese

**Comment by Ibrahim7388** [comment]
[bulk-sponsorships-template.csv](https://github.com/mempool/mempool.js/files/11262752/bulk-sponsorships-template.csv)

**Comment by natsoni** [comment]
Implemented in #170

**Pull request closed without merging**
