### PR TITLE
Update and rename examples/nodejs/mempool-js/bitcoin/addresses.ts to …

### PR DESCRIPTION
**Pull request by terapi09**
…örnekler/düğümler/mempool-js/bitcoin/addresses.ts

### CODE REVIEW

**Comment by tj1162-crypto** [comment]
bitcoin:1B6GYsghz3sf9SEqVgr93kangNbKCfJqkh

**Comment by Erik4569** [comment]
What IS this ? Something win or you are something sending me

**Comment by 1710199225101962** [comment]
> …örnekler/düğümler/mempool-js/bitcoin/addresses.ts

Для чего это?

**Comment by terapi09** [comment]
GDEIQU44GFW63223MVBDNOYICHTGJIEQO523NCLMQFPKPKFDDLN5U3OS

**Pull request closed without merging**
