### PR TITLE
Fix type declaration for getBlocks

### PR DESCRIPTION
**Pull request by AlexLloyd0**

### CODE REVIEW

**Comment by AlexLloyd0** [comment]
Made a couple more changes - please take a look!

**Comment by AlexLloyd0** [comment]
Hi @RaySwag522 , any chance we could get this merged? Thanks :)

**Comment by natsoni** [comment]
ACK for the change on type declaration in functions `getBlocks` and `getBlockTxs` (11c36ee4208f85b166574bac758eff9b2135ecbb and 1d2e229c58c16b269ef1bd77b0f647b46b53b060), but the changes made to the doc in commits 75a921092fb3b7cfccd471f1f9a1ef9a23940d8d and 16d1d95c6603243348e93ae97cfa05a6b537ad72 seem off. Could you remove these commits or further explain the changes please?

**Comment by natsoni** [comment]
Closing because fixed in #167

**Comment by Chu2023js** [comment]
I need help getting my bitcoin and stocks please help

Jesus arau arau

**Pull request closed without merging**
