### PR TITLE
Support a protocol for non-localhost http deployments (e.g. secure tunnels, docker, etc)

### PR DESCRIPTION
**Pull request by 0xFlicker**
A little bit different than https://github.com/mempool/mempool.js/pull/85 in that it allows customizing protocol, which ended up being needed in my test infrastructure

### CODE REVIEW

**Comment by 0xFlicker** [comment]
> Please see the instructions in CONTRIBUTING.md to proceed with this pull request.

where?

**Comment by 0xFlicker** [comment]
found it https://github.com/mempool/mempool/blob/master/CONTRIBUTING.md

working on it

**Comment by 0xFlicker** [comment]
sorry I really did forget about this

this PR was filed right before a large personal tragedy and I just kept on running with my mainline changes

will look at the contributor guide and clean up my branch when I have a moment (as you can see I have been cooking)

**Comment by 0xFlicker** [comment]
looks like I did in fact sign the CLA

also noticing that this PR does almost the same thing as https://github.com/mempool/mempool.js/pull/85

cleaned up my branch to remove my namespace stuff off of it as well as remove unrelated fixes

unrelated note, but I have issues with the `bitcoin.getTx` method with latest mempool api, will try to do a separate pr for that

**Comment by natsoni** [comment]
Hey @0xFlicker, thanks for the PR! I'd like to test it, but there is a conflicting branch name (`main`). Could you please rename your branch, squash your commits and open a new PR? Thanks!

**Comment by 0xFlicker** [comment]
> Could you please rename your branch, squash your commits and open a new PR? Thanks!
will do this weekend

**Comment by 0xFlicker** [comment]
> Hey @0xFlicker, thanks for the PR! I'd like to test it, but there is a conflicting branch name (main). Could you please rename your branch, squash your commits and open a new PR? Thanks!

opened #168

**Pull request closed without merging**
