### PR TITLE
Update blocks.ts

### PR DESCRIPTION
**Pull request by muirronk**

### CODE REVIEW

**Comment by Camille0101** [comment]
https://github.com/mempool/mempool.js/pull/47#issue-1118093137

**Comment by Camille0101** [comment]
https://github.com/mempool/mempool.js/pull/47#issue-1118093137

**Review by Camille0101 — APPROVED** [review]

**Comment by Classof08615** [comment]
Agree

**Comment by MV-801200320** [comment]
[de79c6b3aa8f88982bdab0bbe384a73a4758574603422a9aaaf29ddd6d6ca008]()

**Comment by MV-801200320** [comment]
https://open.delta.app/asset/1000/BTC

**Comment by MV-801200320** [comment]
1P387AySU1HNazBPBGjo1whwYFTYf6fXs4

**Pull request closed without merging**
